global using static GDExtension.GDExtensionCallErrorType;
global using static GDExtension.GDExtensionClassMethodArgumentMetadata;
global using static GDExtension.GDExtensionClassMethodFlags;
global using static GDExtension.GDExtensionInitializationLevel;
global using static GDExtension.GDExtensionVariantOperator;
global using static GDExtension.GDExtensionVariantType;
