<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <PublishAot>true</PublishAot>
    </PropertyGroup>
    <PropertyGroup Condition="$([System.Runtime.InteropServices.RuntimeInformation]::ProcessArchitecture) == X86">
        <DefineConstants>BUILD_32</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="$([System.Runtime.InteropServices.RuntimeInformation]::ProcessArchitecture) == Arm">
        <DefineConstants>BUILD_32</DefineConstants>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\Source\Godot.GDExtension\Godot.GDExtension.csproj" />
        <ProjectReference Include="..\..\Source\Godot.InteropServices\Godot.InteropServices.csproj" />
    </ItemGroup>
</Project>
