<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <PublishAot>true</PublishAot>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Source\Godot\Godot.csproj" />
        <ProjectReference Include="..\Source\Godot.Interop\Godot.Interop.csproj" />
    </ItemGroup>
</Project>
